server:
  port: 8899
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/xiongchao_blog?serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
oss:
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAInwKTTHGeVRyv
  accessKeySecret: UEie2RYgCliXNRHFVTExOAwyiinnFH
  bucketName: flerken-test
swagger:
  enable: true
