server:
  compression:
    enabled: true
  tomcat:
    basedir: logs
    accesslog:
      enabled: true
      directory: .
    max-threads: 3000
  servlet:
    session:
      timeout: 168h
      #      timeout: 60
      cookie:
        name: FLERKEN_SID
#  file-path: C:\project\springboot_xiongchao_blog\src\main\resources\static\ # win
#  file-path: /Users/xiongchao/Desktop/myproject/springboot_xiongchao_blog/src/main/resources/static/ # mac
  file-path: /blog/images/ # Linux
spring:
  profiles:
    active: prod # 运行环境
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 50
      max-wait: 30000
      stat-view-servlet:
        login-username: admin
        login-password: flerken
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:${server.file-path}
