server:
  port: 8090
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/xiongchao_blog?serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
oss:
  endpoint: http://oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAI9eroGKyC6Ep6
  accessKeySecret: imhRjpZKK0U1lKsDDoO3JnfCOvTMmD
  bucketName: flerken-manage
swagger:
  enable: true
